In [1]:
from __future__ import print_function
import torch
import numpy as np

In [2]:
# uninitialised - whatever values were in allocated memory space
x = torch.empty(5, 3)
print(x)

tensor([[1.6114e-19, 1.6020e-19, 4.4721e+21],
        [7.3840e+22, 1.3513e-14, 1.4917e-07],
        [4.4859e+21, 7.2150e+22, 2.4501e-09],
        [7.5553e+28, 5.2839e-11, 1.8888e+31],
        [4.7414e+16, 3.1434e-12, 8.0775e+17]])


In [3]:
# initialise with random values
x = torch.rand(5, 3)
print(x)

tensor([[0.5922, 0.8318, 0.5801],
        [0.2195, 0.0899, 0.5676],
        [0.5548, 0.7034, 0.1194],
        [0.7668, 0.2635, 0.5656],
        [0.3792, 0.1629, 0.0463]])


In [4]:
# initialise with zeroes
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
# initialise with values
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
# set new values
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

# set new values
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)  

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-2.4618,  1.3332, -0.2531],
        [-0.8700,  0.6896,  0.1206],
        [ 0.6153,  0.0836, -1.2130],
        [ 0.2980,  1.1290, -1.2683],
        [-0.9311,  0.4512, -1.1898]])


In [7]:
print(x.size())
# torch.Size supports tuple operations

torch.Size([5, 3])


In [8]:
# three different ways to add tensors
y = torch.rand(5, 3)
print(x + y)
print(torch.add(x, y))
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-2.0390,  1.6890,  0.3668],
        [-0.7056,  1.4961,  0.8660],
        [ 1.1193,  0.4506, -0.9222],
        [ 1.0786,  1.8128, -0.9953],
        [-0.4143,  0.6955, -0.9902]])
tensor([[-2.0390,  1.6890,  0.3668],
        [-0.7056,  1.4961,  0.8660],
        [ 1.1193,  0.4506, -0.9222],
        [ 1.0786,  1.8128, -0.9953],
        [-0.4143,  0.6955, -0.9902]])
tensor([[-2.0390,  1.6890,  0.3668],
        [-0.7056,  1.4961,  0.8660],
        [ 1.1193,  0.4506, -0.9222],
        [ 1.0786,  1.8128, -0.9953],
        [-0.4143,  0.6955, -0.9902]])


In [9]:
# also adding in place
y.add_(x)
print(y)
y.add_(x)
print(y)

tensor([[-2.0390,  1.6890,  0.3668],
        [-0.7056,  1.4961,  0.8660],
        [ 1.1193,  0.4506, -0.9222],
        [ 1.0786,  1.8128, -0.9953],
        [-0.4143,  0.6955, -0.9902]])
tensor([[-4.5009,  3.0222,  0.1137],
        [-1.5756,  2.1857,  0.9866],
        [ 1.7346,  0.5342, -2.1351],
        [ 1.3766,  2.9418, -2.2636],
        [-1.3454,  1.1467, -2.1800]])


In [10]:
# numpy style indexing
print(x[:, 1])

tensor([1.3332, 0.6896, 0.0836, 1.1290, 0.4512])


In [11]:
# reshaping
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [12]:
# extract a scalar value
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.7682])
-0.7681997418403625


In [13]:
# bridge to numpy - note that memory is shared
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [14]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [15]:
# executing in the GPU
print(torch.cuda.is_available())

# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

True
tensor([0.2318], device='cuda:0')
tensor([0.2318], dtype=torch.float64)
