In [1]:
import torch

In [2]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)
print(a, b)

False
True
tensor([[0.9386, 1.2519],
        [1.3102, 1.5350]], requires_grad=True) tensor(6.5209, grad_fn=<SumBackward0>)


In [3]:
x = torch.ones(2, 2, requires_grad=True)
print(x)
y = x + 2
print(y)
print(y.grad_fn)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [4]:
z = (y ** 2) * 3 # same as y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [5]:
out.backward()
# print gradients d(out)/dx
print(x.grad) # this is the x from the top - was [[1, 1], [1, 1]]
# simple differentiaion of 'out' evaluated for x_i = 1
# see https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [9]:
x = torch.randn(3, requires_grad=True)
print(x)

y = x * 2
print(y)
while y.data.norm() < 1000:
    y = y * 2

print('final y')
print(y)

v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
# passing v to backward() gets the vector Jacobian product
y.backward(v)

print(x.grad)

tensor([ 0.9613,  2.4140, -1.4733], requires_grad=True)
tensor([ 1.9227,  4.8281, -2.9467], grad_fn=<MulBackward0>)
final y
tensor([ 492.2007, 1235.9846, -754.3466], grad_fn=<MulBackward0>)
tensor([5.1200e+01, 5.1200e+02, 5.1200e-02])


In [10]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


In [8]:
y.data.norm()

tensor(1674.1472)